apiVersion: v1
kind: PersistentVolume
metadata:
  name: central-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/k8s-bike-shop/central-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: central-db-pvc
  namespace: bike-shop
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
