version: '3.8'

services:
  subotica_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bike_shop_subotica_app
    environment:
      DB_HOST: subotica_db
      DB_PORT: 5432
      DB_NAME: bike_shop_subotica
      DB_USER: postgres
      DB_PASSWORD: password123
      CENTRALNA_URL: http://central_app:5000
    ports:
      - "5002:5000"
    depends_on:
      - subotica_db
      - central_app
    networks:
      - bike_shop_subotica_network
    volumes:
      - ./bike_shop_subotica:/app

  subotica_db:
    image: postgres:15-alpine
    container_name: bike_shop_subotica_db
    environment:
      POSTGRES_DB: bike_shop_subotica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5434:5432"
    volumes:
      - subotica_data:/var/lib/postgresql/data
      - ./sql/lokalna_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bike_shop_subotica_network

volumes:
  subotica_data:
    driver: local

networks:
  bike_shop_subotica_network