# k8s/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: bike-shop

---

# k8s/central-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-bike-shop
  namespace: bike-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-bike-shop
  template:
    metadata:
      labels:
        app: central-bike-shop
    spec:
      containers:
      - name: central-app
        image: katarina59/bike-shop-central:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "central-db-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "central_bike_shop"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password123"

---
apiVersion: v1
kind: Service
metadata:
  name: central-app-service
  namespace: bike-shop
spec:
  selector:
    app: central-bike-shop
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP  # Samo interna komunikacija

---

# k8s/central-db.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-db
  namespace: bike-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-db
  template:
    metadata:
      labels:
        app: central-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "central_bike_shop"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password123"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: central-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: central-db-service
  namespace: bike-shop
spec:
  selector:
    app: central-db
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP

---

# k8s/novi-sad-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novi-sad-bike-shop
  namespace: bike-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novi-sad-bike-shop
  template:
    metadata:
      labels:
        app: novi-sad-bike-shop
    spec:
      containers:
      - name: novi-sad-app
        image: katarina59/bike-shop-novi-sad:latest
        ports:
        - containerPort: 5001
        env:
        - name: DB_HOST
          value: "novi-sad-db-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "bike_shop_novi_sad"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password123"
        - name: CENTRAL_URL
          value: "http://central-app-service:5000"
        - name: GRAD_NAZIV
          value: "Novi Sad"

---
apiVersion: v1
kind: Service
metadata:
  name: novi-sad-app-service
  namespace: bike-shop
spec:
  selector:
    app: novi-sad-bike-shop
  ports:
  - port: 5001
    targetPort: 5001
  type: ClusterIP

---

# k8s/novi-sad-db.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novi-sad-db
  namespace: bike-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novi-sad-db
  template:
    metadata:
      labels:
        app: novi-sad-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "bike_shop_novi_sad"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password123"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: novi-sad-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: novi-sad-db-service
  namespace: bike-shop
spec:
  selector:
    app: novi-sad-db
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP

---

# k8s/kragujevac-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kragujevac-bike-shop
  namespace: bike-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kragujevac-bike-shop
  template:
    metadata:
      labels:
        app: kragujevac-bike-shop
    spec:
      containers:
      - name: kragujevac-app
        image: katarina59/bike-shop-kragujevac:latest
        ports:
        - containerPort: 5002
        env:
        - name: DB_HOST
          value: "kragujevac-db-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "bike_shop_kragujevac"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password123"
        - name: CENTRAL_URL
          value: "http://central-app-service:5000"
        - name: GRAD_NAZIV
          value: "Kragujevac"

---
apiVersion: v1
kind: Service
metadata:
  name: kragujevac-app-service
  namespace: bike-shop
spec:
  selector:
    app: kragujevac-bike-shop
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP

---

# k8s/kragujevac-db.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kragujevac-db
  namespace: bike-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kragujevac-db
  template:
    metadata:
      labels:
        app: kragujevac-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "bike_shop_kragujevac"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password123"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: kragujevac-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: kragujevac-db-service
  namespace: bike-shop
spec:
  selector:
    app: kragujevac-db
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP

---

# k8s/subotica-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subotica-bike-shop
  namespace: bike-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subotica-bike-shop
  template:
    metadata:
      labels:
        app: subotica-bike-shop
    spec:
      containers:
      - name: subotica-app
        image: katarina59/bike-shop-subotica:latest
        ports:
        - containerPort: 5003
        env:
        - name: DB_HOST
          value: "subotica-db-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "bike_shop_subotica"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password123"
        - name: CENTRALNA_URL
          value: "http://central-app-service:5000"
        - name: GRAD_NAZIV
          value: "Subotica"

---
apiVersion: v1
kind: Service
metadata:
  name: subotica-app-service
  namespace: bike-shop
spec:
  selector:
    app: subotica-bike-shop
  ports:
  - port: 5003
    targetPort: 5003
  type: ClusterIP

---

# k8s/subotica-db.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subotica-db
  namespace: bike-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subotica-db
  template:
    metadata:
      labels:
        app: subotica-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "bike_shop_subotica"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password123"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: subotica-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: subotica-db-service
  namespace: bike-shop
spec:
  selector:
    app: subotica-db
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP